wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: huggingface
    huggingface_version: 4.21.1
    is_jupyter_run: false
    is_kaggle_kernel: true
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.9.12
    start_time: 1660041437
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 50
      - 53
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.9.12
      5: 0.12.17
      6: 4.21.1
      8:
      - 2
      - 5
